# Generated by Django 4.2.3 on 2023-09-23 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Catalog",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="blog",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.DeleteModel(
            name="Social",
        ),
        migrations.DeleteModel(
            name="Blog",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
