# Generated by Django 4.2.3 on 2023-10-05 21:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="images",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default=None,
                storage=django.core.files.storage.FileSystemStorage("base/static"),
                upload_to="img/products",
            ),
        ),
        migrations.AlterField(
            model_name="addressbook",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage("base/static"),
                upload_to="img/users",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage("base/static"),
                upload_to="img/blog",
            ),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage("base/static"),
                upload_to="img/catalog",
            ),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
