# Generated by Django 4.2.3 on 2023-10-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_remove_product_images_product_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.IntegerField(default=None),
        ),
    ]
