# Generated by Django 4.2.6 on 2023-10-18 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_cart"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
