# Generated by Django 4.2.6 on 2023-10-20 20:18

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_delete_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                storage=django.core.files.storage.FileSystemStorage("base/static"),
                upload_to="img/products",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image3",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                storage=django.core.files.storage.FileSystemStorage("base/static"),
                upload_to="img/products",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image4",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                storage=django.core.files.storage.FileSystemStorage("base/static"),
                upload_to="img/products",
            ),
        ),
    ]
