# Generated by Django 4.2.6 on 2023-10-20 20:26

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0013_color_alter_product_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image2",
            field=models.ImageField(
                default=None,
                storage=django.core.files.storage.FileSystemStorage("base/static"),
                upload_to="img/products",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image3",
            field=models.ImageField(
                default=None,
                storage=django.core.files.storage.FileSystemStorage("base/static"),
                upload_to="img/products",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image4",
            field=models.ImageField(
                default=None,
                storage=django.core.files.storage.FileSystemStorage("base/static"),
                upload_to="img/products",
            ),
        ),
    ]
