# Generated by Django 4.2.6 on 2023-10-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0014_alter_product_image2_alter_product_image3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
