# Generated by Django 4.2.6 on 2023-10-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0015_alter_product_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=5),
        ),
    ]
