# Generated by Django 4.2.6 on 2023-10-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0016_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="delivery",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
