# Generated by Django 4.2.6 on 2023-10-21 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0018_remove_product_delivery"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="cataglog",
            new_name="catalog",
        ),
    ]
