# Generated by Django 4.2.6 on 2023-11-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0022_addressbook_country_alter_addressbook_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressbook",
            name="address",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="addressbook",
            name="country",
            field=models.CharField(
                blank=True, default="Nigeria", max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="addressbook",
            name="phone_number",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="addressbook",
            name="state",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
