# Generated by Django 4.2.6 on 2023-11-10 03:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0025_product_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_created=True, auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("summary", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        storage=django.core.files.storage.FileSystemStorage(
                            "base/static"
                        ),
                        upload_to="img/blog",
                    ),
                ),
            ],
        ),
    ]
